sudo: false
language: erlang
otp_release:
  - 21.0.3
  - 20.3
  - 19.3
before_install:
  - ./ci before_install "${PWD:?}"/rebar3
install:
  - ./ci install "${PWD:?}"/rebar3
script:
  - ./ci script "${PWD:?}"/rebar3
cache:
  directories:
    - .plt
